language: python

python:
  - "3.6"

before install:
  - cd ./flight_backend

install:
  - pipenv install
  - pip install coverage
  - pip install coveralls

script:
  - coverage run manage.py test
  - coverage report

after_script:
  - coveralls
