language: python

python:
  - "3.6"

service:
  - postgresql

addons:
  postgresql: '9.4'

install:
  - pipenv install
  - pipenv install coverage
  - pipenv install coveralls

before_script:
  - cd flight_backend
  - export DB_NAME="airtech_backend_test"
  - psql -c 'create database airtech_backend_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run manage.py test
  - coverage report

after_script:
  - coveralls
