language: python

python:
  - "3.6"

install:
  - pipenv install
  - pipenv install coverage
  - pipenv install coveralls

before script:
  - cd ./flight_backend

script:
  - coverage run manage.py test
  - coverage report

after_script:
  - coveralls
