# Generated by Django 2.2.3 on 2019-08-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='phone_number',
        ),
    ]
